# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Items',
            new_name='item',
        ),
    ]
